# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "entries", :force => true do |t|
    t.column "message",  :string
    t.column "datetime", :string
    t.column "digest",   :string
    t.column "filename", :string
  end

  create_table "queries", :force => true do |t|
    t.column "parameters", :string
  end

end
